#!/usr/bin/env python

'''description'''

import argparse
import os
import sys
# Temporary
sys.path.append('./modules')
import picc.coff as coff

__script__ = 'picc-objdump'
__author__ = 'Antonio Serrano Hernandez'
__copyright__ = 'Copyright (C) 2016 Antonio Serrano Hernandez'
__version__ = '0.0.1'
__license__ = 'GPL'
__maintainer__ = 'Antonio Serrano Hernandez'
__email__ = 'toni.serranoh@gmail.com'
__status__ = 'Development'
__homepage__ = 'https://github.com/aserranoh/picc'

VERSION_STRING = '''\
%(prog)s {version}
{copyright}
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.\
'''.format(version=__version__, copyright=__copyright__)

HELP_EPILOG = '''\
Report bugs to: {email}
picc home page: {homepage}
'''.format(email=__email__, homepage=__homepage__)

def main():
    '''Entry point for the program picc-objdump.
    
    Loads the contents of the file given by parameter in a Coff object and
    print its fields.
    '''
    parser = argparse.ArgumentParser(prog=__script__, epilog=HELP_EPILOG,
        formatter_class=argparse.RawTextHelpFormatter)
    # Objfile is the main argument, the input file
    parser.add_argument('objfile', help='COFF file to explore')
    parser.add_argument('--version', action='version', version=VERSION_STRING)
    args = parser.parse_args()

    obj = coff.readcoff(args.objfile)
    print(obj)

if __name__ == '__main__':
    main()

